MOUSEKEY_ENABLE     = no     # Mouse keys
RGBLIGHT_ENABLE     = yes    # Enable WS2812 RGB underlight.
VIA_ENABLE          = yes         # Enable VIA
OLED_DRIVER_ENABLE  = yes
LTO_ENABLE          = yes
# TAP_DANCE_ENABLE = yes
COMBO_ENABLE     = yes
NKRO_ENABLE      = yes
SWAP_HANDS_ENABLE= no  # Allow swapping hands of keyboard
EXTRAFLAGS += -flto
